Do not run the checks if the cronspool directory is not readable or does not exist, warn if this is the case

diff --git a/systems/HPUX/gen_cron b/systems/HPUX/gen_cron
--- a/systems/HPUX/gen_cron
+++ b/systems/HPUX/gen_cron
@@ -16,12 +16,24 @@
 #     Please see the file `COPYING' for the complete copyright notice.
 #
 # gen_cron - 06/14/93
+# HPUX/gen_cron  - 02/10/2018 - jfs - Exit if the directory does not exist
+#                   or is not readable
+#
 #
 #-----------------------------------------------------------------------------
 #
 
 outfile=$1
 > $outfile
+
+if [ ! -d "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cron spool directory $CRONSPOOL does not exist."
+    exit 1
+fi
+if [ ! -r "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cannot read contents of spool directory $CRONSPOOL."
+    exit 1
+fi
 
 (
   cd $CRONSPOOL
diff --git a/systems/SunOS/gen_cron b/systems/SunOS/gen_cron
--- a/systems/SunOS/gen_cron
+++ b/systems/SunOS/gen_cron
@@ -18,6 +18,8 @@
 # SunOS/gen_cron - 06/14/93
 #
 # SunOS/gen_cron - 08/12/2002 - jfs - Fixed so that it works standalone
+# SunOS/gen_cron  - 02/10/2018 - jfs - Exit if the directory does not exist
+#                   or is not readable
 #
 #-----------------------------------------------------------------------------
 #
@@ -33,9 +35,19 @@ outfile=$1
 #	exit 1
 #fi
 
+
 [ -n "$outfile" ] && > $outfile
 
 [ ! -n "$GETUSERHOME" ] && GETUSERHOME=echo
+
+if [ ! -d "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cron spool directory $CRONSPOOL does not exist."
+    exit 1
+fi
+if [ ! -r "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cannot read contents of spool directory $CRONSPOOL."
+    exit 1
+fi
 
 (
   cd $CRONSPOOL
diff --git a/systems/Tru64/5/gen_cron b/systems/Tru64/5/gen_cron
--- a/systems/Tru64/5/gen_cron
+++ b/systems/Tru64/5/gen_cron
@@ -17,6 +17,8 @@
 #     Please see the file `COPYING' for the complete copyright notice.
 #
 # Tru64/5/gen_cron - 06/14/93
+# Tru64/5/gen_cron  - 02/10/2018 - jfs - Exit if the directory does not exist
+#                   or is not readable
 #
 #-----------------------------------------------------------------------------
 # TODO: Fix the check_crontabs and gen_cron files to perform the checks
@@ -31,6 +33,16 @@ TigerInstallDir="/opt/tiger"
 
 outfile=$1
 > $outfile
+
+if [ ! -d "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cron spool directory $CRONSPOOL does not exist."
+    exit 1
+fi
+if [ ! -r "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cannot read contents of spool directory $CRONSPOOL."
+    exit 1
+fi
+
 
 (
   cd $CRONSPOOL
diff --git a/systems/default/gen_cron b/systems/default/gen_cron
--- a/systems/default/gen_cron
+++ b/systems/default/gen_cron
@@ -17,12 +17,24 @@
 #
 # generic SYSV/gen_cron - 07/31/97
 #
+# gen_cron  - 02/10/2018 - jfs - Exit if the directory does not exist
+#                   or is not readable
+#
 #-----------------------------------------------------------------------------
 #
 
 
 outfile=$1
 > $outfile
+
+if [ ! -d "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cron spool directory $CRONSPOOL does not exist."
+    exit 1
+fi
+if [ ! -r "$CRONSPOOL" ] ; then
+    echo "--ERROR-- Cannot read contents of spool directory $CRONSPOOL."
+    exit 1
+fi
 
 (
   cd $CRONSPOOL
