Clean up the cron output file befoe using as this might contain --ERROR-- or --WARN-- messages from gen_cron which leads to interpretation problems (Debian bug #839635)

diff --git a/scripts/check_crontabs b/scripts/check_crontabs
--- a/scripts/check_crontabs
+++ b/scripts/check_crontabs
@@ -38,6 +38,10 @@
 #                        correct errors
 # check_crontabs  - 04/20/1999 Modified by Advanced Research Corp (R) to 
 #                        correct errors
+# check_crontabs  - 02/10/2018 - jfs - Clean up the cron output file befoe
+#                        using as this might contain --ERROR-- or --WARN--
+#                        messages from gen_cron which leads to interpretation
+#                        problems (Debian bug #839635)
 # 
 #-----------------------------------------------------------------------------
 #
@@ -76,7 +80,7 @@ done
 # elements are set.
 #
 [ "$Tiger_TESTMODE" = 'Y' ] && {
-  haveallcmds AWK BASENAME CAT GEN_CRON_FILES LS RM TR SED GREP OUTPUTMETHOD || exit 1
+  haveallcmds AWK BASENAME CAT GEN_CRON_FILES LS MV RM TR SED GREP OUTPUTMETHOD || exit 1
   haveallfiles BASEDIR WORKDIR || exit 1
   
   echo "--CONFIG-- [init003c] $0: Configuration ok..."
@@ -87,7 +91,7 @@ done
 echo
 echo "# Performing check of \`cron' entries..."
 
-haveallcmds AWK BASENAME CAT GEN_CRON_FILES LS RM TR SED GREP OUTPUTMETHOD || exit 1
+haveallcmds AWK BASENAME CAT GEN_CRON_FILES LS MV RM TR SED GREP OUTPUTMETHOD || exit 1
 haveallfiles BASEDIR WORKDIR || exit 1
 
 
@@ -102,6 +106,10 @@ lowner=
 
 {
   $GEN_CRON_FILES $WORKDIR/cron.in.$$
+
+  # Remove any warnings / errors that might have been generated by the gen_cron script 
+  $CAT $WORKDIR/cron.in.$$ | $GREP -v -- "--" >$WORKDIR/cron.fix.$$ 
+  $MV $WORKDIR/cron.fix.$$  $WORKDIR/cron.in.$$
 
   #
   # Be careful if you muck around in this loop.  Since we are reading
